# Generated by Django 2.1 on 2018-11-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_transaction'),
    ]

    operations = [
        migrations.CreateModel(
            name='SalesFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saved_file', models.FileField(upload_to='uploads')),
            ],
        ),
    ]
